version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: backend
    ports:
      - "5000:8080"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: xackaton_db
    ports:
      - "5432:5432"

  frontend:
      user: 1000:1000
      volumes:
          - ./frontend:/var/www
      build:
          context: ./docker/frontend
          dockerfile: Dockerfile
      container_name: frontend
      working_dir: /var/www
      ports:
          - 3000:80

  nginx:
    image: nginx:alpine
    tty: true
    restart: always
    volumes:
      - ./backend:/var/www/backend/
      - ./frontend:/var/www/frontend/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/log/:/var/log/nginx/
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
